### ISSUE TITLE
2 Scene (4 button) controllers - one no longer working

### ISSUE THREAD

**Issue by henkbb36org** [TedTolboom/com.hank-tech#2]
Hi! I am using two Hank 4 button scene controllers and they were both working well before. I am trying to get both working again after I had to reset the zwave network on Homey. After resetting zwave on Homey I have also reset both scene controllers back to factory settings. That worked fine. Next I included both controllers again using the installation procedure of your app, the installation worked as expected and they both appeared as devices again on Homey. However, one controller works fine, the other doesn't. Now what happens: when I press the buttons on controller with node id 6 (see logfile), traffic appears in the log but my flows are NOT fired. I am using the correct device in the flow and when I test run the flow from the menu it works. Node id 4 is the other controller and it works fine. I checked device settings and firmware of both controllers, they are equal. I am puzzled... The problem occurs on Homey firmware 1.5.7 but also 1.5.8. Any ideas?
[zwavelog.txt](https://github.com/TedTolboom/com.hank-tech/files/1793734/zwavelog.txt)

**Comment by TedTolboom** [comment]
Hi @henkbb36org,

I tried to reproduce this issue, but I'm not able to...
In the latest update, v1.0.3 (in the app store), I have updated the drivers for both Scene controllers to the latest status (same parsers as also used for the Remotec ZRC-90)..

Can you try this app update and check if this solves your issue?

Thanks.

**Comment by TedTolboom** [comment]
@henkbb36org is this issue still occuring?

**Comment by TedTolboom** [comment]
Closed due to inactivity
