### ISSUE TITLE
Hank Smart plug

### ISSUE THREAD

**Issue by Kstoffe** [TedTolboom/com.hank-tech#4]
I can´t turn the smart plug on or off with Homey. I can se the power  and powermeter. But it will not respond to on/off.

It has not worked since I plugged it in for the first time.

**Comment by TedTolboom** [comment]
@Kstoffe is this issue still occuring?
Did you try to remove and re-include the smart plug?

I don't have the smart plug myself. If this issue is still occuring, I'll see if I can get my hands on one to reproduce.

**Comment by Kstoffe** [comment]
Hi!

It is working now!
So the problem is solved!




Den sön 23 sep. 2018 10:43dT <notifications@github.com> skrev:
