### ISSUE TITLE
Removed light bulb is still connected somehow? 

### ISSUE THREAD

**Issue by TechnoX** [TedTolboom/com.hank-tech#9]
Hi,

I just helped my dad to install his new Homey. Worked like a charm until he lit up and turned off the hank RGB light bulb through the app several times during a short amount of time. It hanged up in on state.

Then I tried to remove the device from the app and add it again. It failed.

I get status.already_added when trying to add it again. After altering the power three times. 
See image: http://i64.tinypic.com/33o194y.jpg

Any ideas? 

Thanks in advance :)

**Comment by TedTolboom** [comment]
@TechnoX Please try to remove it from the Z-wave settings > remove Z-wave device and activate the RGB bulb according to the instructions in the manual

> To remove the RGB BULB from the Z-Wave network:
> (1) Screw in the RGB BULB.
> (2) Set the Z-Wave network main controller into excluding mode
> (see Z-Wave controller operating manual).
> (3) Toggle the wall switch off and on 3 times quickly(within 3
> and the final ending position of the wall switch must be on),
> if the exclusion is successful, the RGB BULB will blink fast in orange for less than 5 seconds and then keep on for 3 seconds. RGB BULB will keep on warm white after the exclusion procedure is finished.
